const ICON_SRC_MAPPING: Record<string, string> = {
  "404": "/assets/admin/icons/404.svg",
  angle: "/assets/admin/icons/ic_angle.png",
  arrow_white: "/assets/admin/icons/ic_arrow_white.svg",
  dropdown_check_yellow: "/assets/admin/icons/ic_dropdown_check_yellow.png",
  empty_image: "/assets/admin/icons/ic_empty_image.svg",
  road_sign: "/assets/admin/icons/ic_road_sign.svg",
  round_arrow: "/assets/admin/icons/ic_round_arrow.svg",
  setting: "/assets/admin/icons/ic_setting.png",
  plus: "/assets/admin/icons/ic_plus.svg",
  plus_white: "/assets/admin/icons/ic_plus_white.svg",
  checkbox_disabled_checked:
    "/assets/admin/icons/ic_checkbox_disabled_checked.png",
  dnd: "/assets/admin/icons/ic_dnd.png",
  double_arrow_black: "/assets/admin/icons/ic_double_arrow_black.svg",
  double_arrow_white: "/assets/admin/icons/ic_double_arrow_white.svg",
  minus: "/assets/admin/icons/ic_minus.svg",
  sidebar_product_active: "/assets/admin/icons/ic_sidebar_product_active.png",
  sidebar_setting: "/assets/admin/icons/ic_sidebar_setting.png",
  sidebar_setting_active: "/assets/admin/icons/ic_sidebar_setting_active.png",
  sidebar_statistics: "/assets/admin/icons/ic_sidebar_statistics.png",
  sidebar_statistics_active:
    "/assets/admin/icons/ic_sidebar_statistics_active.png",
  sidebar_user: "/assets/admin/icons/ic_sidebar_user.png",
  sidebar_user_active: "/assets/admin/icons/ic_sidebar_user_active.png",
  table_arrow: "/assets/admin/icons/ic_table_arrow.png",
  x: "/assets/admin/icons/ic_x.png",
  x02: "/assets/admin/icons/ic_x02.png",
  x_dark: "/assets/admin/icons/ic_x_dark.png",
  x_hover: "/assets/admin/icons/ic_x_hover.png",
  sidebar_board: "/assets/admin/icons/ic_sidebar_board.png",
  sidebar_board_active: "/assets/admin/icons/ic_sidebar_board_active.png",
  sidebar_cart: "/assets/admin/icons/ic_sidebar_cart.png",
  sidebar_cart_active: "/assets/admin/icons/ic_sidebar_cart_active.png",
  sidebar_collection: "/assets/admin/icons/ic_sidebar_collection.png",
  sidebar_collection_active:
    "/assets/admin/icons/ic_sidebar_collection_active.png",
  sidebar_design: "/assets/admin/icons/ic_sidebar_design.png",
  sidebar_design_active: "/assets/admin/icons/ic_sidebar_design_active.png",
  sidebar_home: "/assets/admin/icons/ic_sidebar_home.png",
  sidebar_home_active: "/assets/admin/icons/ic_sidebar_home_active.png",
  sidebar_product: "/assets/admin/icons/ic_sidebar_product.png",
  profile_dark: "/assets/admin/icons/ic_profile_dark.png",
  profile_light: "/assets/admin/icons/ic_profile_light.png",
  radio_check: "/assets/admin/icons/ic_radio_check.png",
  radio_uncheck: "/assets/admin/icons/ic_radio_uncheck.png",
  reload: "/assets/admin/icons/ic_reload.png",
  search_gray: "/assets/admin/icons/ic_search_gray.png",
  download_gray: "/assets/admin/icons/ic_download_gray.png",
  download_white: "/assets/admin/icons/ic_download_white.png",
  dropdown_check: "/assets/admin/icons/ic_dropdown_check.png",
  filter: "/assets/admin/icons/ic_filter.png",
  logo: "/assets/admin/icons/ic_logo.png",
  celendar_gray: "/assets/admin/icons/ic_celendar_gray.png",
  checkbox: "/assets/admin/icons/ic_checkbox.png",
  checkbox_disabled: "/assets/admin/icons/ic_checkbox_disabled.png",
  checkbox_empty: "/assets/admin/icons/ic_checkbox_empty.png",
  double_arrow: "/assets/admin/icons/ic_double_arrow.png",
  arrow_gray: "/assets/admin/icons/ic_arrow_gray.png",
  arrow_gray02: "/assets/admin/icons/ic_arrow_gray02.png",
  arrow_gray_down: "/assets/admin/icons/ic_arrow_gray_down.png",
  arrow_gray_left: "/assets/admin/icons/ic_arrow_gray_left.png",
  arrow_gray_right: "/assets/admin/icons/ic_arrow_gray_right.png",
  arrow_gray_up: "/assets/admin/icons/ic_arrow_gray_up.png",
  arrow_left: "/assets/admin/icons/ic_arrow_left.svg",
  arrow_right: "/assets/admin/icons/ic_arrow_right.svg",
  camera: "/assets/admin/icons/ic_camera.png",
  xbox: "/assets/admin/icons/ic_xbox.png",
  info: "/assets/admin/icons/ic_info.svg",
   ic_check: "/assets/admin/icons/ic_check.svg",
};

export default ICON_SRC_MAPPING;
